import { ArrowRight, CheckCircle2, MapPin, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import type { Opportunity } from "@/data/mock";

export default function OpportunityCard({ opportunity, compact = false }: { opportunity: Opportunity; compact?: boolean }) {
  return <article className="group rounded-xl border border-slate-200 bg-white p-5 shadow-[0_8px_32px_rgba(15,23,42,.04)] transition-all duration-300 hover:-translate-y-1 hover:border-amber-300 hover:shadow-[0_16px_40px_rgba(11,60,42,.10)]" data-testid={`opportunity-card-${opportunity.id}`}>
    <div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-sm bg-amber-50 px-2 py-1 text-[10px] font-bold uppercase tracking-[0.12em] text-amber-800" data-testid={`opportunity-type-${opportunity.id}`}>{opportunity.type}</span>{opportunity.verified && <span className="inline-flex items-center gap-1 text-[11px] font-semibold text-emerald-700" data-testid={`opportunity-verified-${opportunity.id}`}><CheckCircle2 size={13} /> Verified employer</span>}</div><h3 className="mt-3 text-lg font-bold text-[#0B3C2A]" data-testid={`opportunity-title-${opportunity.id}`}>{opportunity.title}</h3><p className="mt-1 text-sm font-medium text-slate-600" data-testid={`opportunity-organisation-${opportunity.id}`}>{opportunity.organisation}</p></div><div className="rounded-lg bg-[#0B3C2A] px-3 py-2 text-center text-white" data-testid={`opportunity-match-${opportunity.id}`}><p className="font-mono text-xl font-semibold leading-none">{opportunity.match}%</p><p className="mt-1 text-[9px] uppercase tracking-wider text-emerald-100">match</p></div></div>
    <div className="mt-5 flex flex-wrap gap-x-4 gap-y-2 text-xs text-slate-500"><span className="inline-flex items-center gap-1"><MapPin size={14} className="text-amber-700" />{opportunity.location}</span><span>{opportunity.stipend}</span><span>{opportunity.duration}</span><span>{opportunity.mode}</span></div>
    {!compact && <><div className="mt-5 flex flex-wrap gap-2">{opportunity.skills.slice(0, 4).map((skill) => <span key={skill} className="rounded-full border border-emerald-100 bg-emerald-50 px-2.5 py-1 text-[11px] font-medium text-emerald-800" data-testid={`opportunity-skill-${opportunity.id}-${skill.toLowerCase().replaceAll(" ", "-")}`}>{skill}</span>)}<span className="rounded-full border border-amber-200 bg-amber-50 px-2.5 py-1 text-[11px] font-medium text-amber-800">+{opportunity.skills.length - 4} more</span></div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><p className="inline-flex items-center gap-1.5 text-xs font-medium text-slate-600"><Sparkles size={14} className="text-amber-600" /> {opportunity.gaps.length} skill gaps become next steps</p><Link to={`/opportunities/${opportunity.id}`} className="inline-flex items-center gap-1 text-sm font-bold text-[#0B3C2A] transition-transform group-hover:translate-x-0.5" data-testid={`opportunity-view-${opportunity.id}`}>View opportunity <ArrowRight size={15} /></Link></div></>}
  </article>;
}