import { useMutation, useQuery } from "@tanstack/react-query";
import { BadgeCheck, Download, FileCheck2, GraduationCap, ShieldCheck } from "lucide-react";
import DashboardShell from "@/components/DashboardShell";
import { apiGet } from "@/lib/api";
import type { AssessmentResult, CareerPassportDocument, PersistedInternship, StudentProfile } from "@/lib/types";

export default function CareerPassport() {
  const profile = useQuery({ queryKey: ["profile", "me"], queryFn: () => apiGet<StudentProfile>("/profile/me") });
  const assessment = useQuery({ queryKey: ["assessment", "latest"], queryFn: () => apiGet<AssessmentResult | null>("/assessments/latest") });
  const internships = useQuery({ queryKey: ["internships", "me"], queryFn: () => apiGet<PersistedInternship[]>("/internships/me") });
  const download = useMutation({ mutationFn: () => apiGet<CareerPassportDocument>("/profile/passport"), onSuccess: (document) => { const binary = atob(document.content_base64); const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes], { type: document.media_type })); const anchor = window.document.createElement("a"); anchor.href = url; anchor.download = document.filename; anchor.click(); URL.revokeObjectURL(url); } });
  const readiness = assessment.data?.readiness ?? 0;

  return <DashboardShell role="student" mode="real"><div className="mx-auto max-w-6xl px-4 py-10 sm:px-8" data-testid="career-passport-page">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="font-mono text-xs font-semibold uppercase tracking-[0.17em] text-[#A66D12]">PRAMANA · CAREER PASSPORT</p><h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">Your verified direction, experience and evidence.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Preview the profile employers can understand, then download a professionally formatted PDF.</p></div><button onClick={() => download.mutate()} disabled={download.isPending || !profile.data} className="inline-flex h-11 items-center justify-center gap-2 rounded-md bg-[#174A3A] px-5 text-sm font-bold text-white disabled:opacity-60" data-testid="career-passport-download-button"><Download size={16} />{download.isPending ? "Preparing PDF…" : "Download PDF"}</button></div>
    {profile.isPending && <div className="mt-8 rounded-xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Building your passport preview…</div>}
    {profile.data && <article className="mt-8 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-[0_18px_55px_rgba(15,23,42,.07)]" data-testid="career-passport-preview">
      <header className="border-b border-slate-200 bg-slate-50 p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.18em] text-[#A66D12]">SAMANVAYA CAREER PASSPORT</p><h2 className="mt-3 text-3xl font-bold text-slate-900">{profile.data.name}</h2><p className="mt-2 text-sm text-slate-600">{profile.data.education} · {profile.data.ayush_system}</p><p className="mt-1 text-sm text-slate-500">{profile.data.institution} · Graduating {profile.data.graduation_year}</p></div><div className="rounded-lg border border-amber-200 bg-amber-50 px-5 py-4 text-right"><p className="font-mono text-3xl font-bold text-slate-900" data-testid="passport-readiness-score">{readiness}%</p><p className="text-xs text-slate-500">Career readiness</p></div></div></header>
      <div className="grid gap-px bg-slate-200 md:grid-cols-3"><Metric icon={BadgeCheck} value={String(profile.data.skills.filter((skill) => skill.provenance !== "Self-declared").length)} label="Verified skills" /><Metric icon={FileCheck2} value={String(profile.data.portfolio_evidence.length)} label="Portfolio evidence" /><Metric icon={GraduationCap} value={String(internships.data?.length ?? 0)} label="Internship records" /></div>
      <div className="grid gap-8 p-6 sm:p-8 lg:grid-cols-[1.05fr_.95fr]"><section data-testid="passport-skills-section"><h3 className="text-lg font-bold text-slate-900">Skills with provenance</h3><div className="mt-5 space-y-4">{profile.data.skills.map((skill) => <div key={skill.name}><div className="flex items-center justify-between text-sm"><span className="font-semibold text-slate-800">{skill.name}</span><span className="font-mono text-[#174A3A]">{skill.level}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#C58B2A]" style={{ width: `${skill.level}%` }} /></div><p className="mt-1 flex items-center gap-1 text-[11px] text-slate-500"><ShieldCheck size={12} />{skill.provenance} · {skill.evidence || "Evidence not added"}</p></div>)}</div></section><section data-testid="passport-experience-section"><h3 className="text-lg font-bold text-slate-900">Verified experience</h3><div className="mt-5 space-y-3">{internships.data?.map((internship) => <div key={internship.id} className="rounded-lg border border-slate-200 p-4"><p className="font-bold text-slate-900">{internship.opportunity_title}</p><p className="mt-1 text-xs text-slate-500">{internship.organisation} · Week {internship.week} of {internship.total_weeks}</p><p className="mt-3 text-xs leading-5 text-slate-600">Deliverable: {internship.deliverable}</p></div>)}</div><h3 className="mt-7 text-lg font-bold text-slate-900">Portfolio</h3><div className="mt-4 space-y-3">{profile.data.portfolio_evidence.map((item) => <div key={`${item.title}-${item.date}`} className="border-l-2 border-[#C58B2A] pl-3"><p className="text-sm font-semibold text-slate-800">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.evidence_type} · {item.issuer} · {item.date}</p></div>)}</div></section></div>
      <footer className="border-t border-slate-200 px-6 py-4 text-xs text-slate-500 sm:px-8">Prototype career document · Verify evidence with the listed issuer · Not an official government credential</footer>
    </article>}
    {download.isError && <p className="mt-4 text-sm text-rose-700" role="alert" data-testid="passport-download-error">We couldn’t generate the PDF. Your saved profile is unchanged.</p>}
  </div></DashboardShell>;
}

function Metric({ icon: Icon, value, label }: { icon: typeof BadgeCheck; value: string; label: string }) { return <div className="bg-white p-5"><Icon size={18} className="text-[#A66D12]" /><p className="mt-3 font-mono text-3xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>; }