import { Link } from "react-router-dom";
import { ArrowRight, BadgeCheck, BookOpenCheck, BriefcaseBusiness, Building2, FileCheck2, GraduationCap, Handshake, Landmark, Sparkles, UsersRound } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import AntigravityCanvas from "@/components/AntigravityCanvas";
import BrandMark from "@/components/BrandMark";
import OpportunityCard from "@/components/OpportunityCard";
import { opportunities } from "@/data/mock";

const journey: Array<{ label: string; copy: string; icon: LucideIcon }> = [
  { label: "Assess", copy: "Build an evidence-led view of readiness", icon: BookOpenCheck },
  { label: "Match", copy: "Understand fit, gaps and next steps", icon: Sparkles },
  { label: "Mentor", copy: "Learn from alumni and practitioners", icon: UsersRound },
  { label: "Work", copy: "Complete defined internship outcomes", icon: BriefcaseBusiness },
  { label: "Verify", copy: "Carry credible proof into your next match", icon: FileCheck2 },
];

export default function Home() {
  return <div className="min-h-screen bg-white text-slate-900" data-testid="home-page">
    <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur" data-testid="home-header"><div className="mx-auto flex min-h-20 max-w-7xl items-center justify-between gap-4 px-4 py-3 sm:px-6 lg:px-8"><Link to="/" aria-label="SAMANVAYA home" data-testid="home-brand-link"><BrandMark testIdPrefix="home-header" /></Link><nav className="hidden items-center gap-6 lg:flex" aria-label="Primary navigation">{[["How it works", "/how-it-works"], ["Opportunities", "/opportunities"], ["Alumni", "/alumni"], ["Mentors", "/mentors"]].map(([label, href]) => <Link key={href} to={href} className="text-sm font-medium text-slate-600 hover:text-slate-950" data-testid={`home-nav-${label.toLowerCase().replaceAll(" ", "-")}`}>{label}</Link>)}</nav><div className="flex items-center gap-2"><Link to="/login" className="hidden px-3 py-2 text-sm font-semibold text-slate-700 sm:inline-flex" data-testid="home-login-link">Sign in</Link><Link to="/opportunities" className="inline-flex h-10 items-center rounded-md bg-[#174A3A] px-4 text-sm font-bold text-white" data-testid="home-get-started-link">Explore <ArrowRight size={15} className="ml-2" /></Link></div></div></header>

    <main>
      <section className="relative overflow-hidden border-b border-slate-200 bg-[#FCFCFA]" data-testid="home-hero"><AntigravityCanvas /><div className="relative mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:px-8 lg:py-24"><div><div className="inline-flex items-center gap-2 rounded-full border border-amber-200 bg-amber-50 px-3 py-1.5 text-xs font-semibold text-[#8A570E]" data-testid="hero-availability-badge"><Landmark size={14} />SIH 2026 · Digital public infrastructure prototype</div><h1 className="mt-7 max-w-3xl text-4xl font-bold leading-[1.08] tracking-tight text-slate-950 sm:text-5xl lg:text-[4rem]" data-testid="hero-headline">Connecting AYUSH talent with the opportunities that move the sector forward.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-600 sm:text-lg" data-testid="hero-description">SAMANVAYA connects students, alumni, mentors, institutions and AYUSH enterprises through skills, internships, mentorship and verified career evidence.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/opportunities" className="inline-flex h-12 items-center justify-center gap-2 rounded-md bg-[#174A3A] px-6 text-sm font-bold text-white shadow-sm hover:bg-[#10382C]" data-testid="hero-explore-opportunities-button">Explore opportunities <ArrowRight size={17} /></Link><Link to="/login?next=/app/student/pariksha" className="inline-flex h-12 items-center justify-center gap-2 rounded-md border border-slate-300 bg-white px-6 text-sm font-bold text-slate-800 hover:border-[#C58B2A]" data-testid="hero-assess-skills-button"><BookOpenCheck size={17} />Assess my skills</Link></div><p className="mt-7 text-xs leading-5 text-slate-500">Prototype, not an official Ministry service. Government and credential integrations are clearly marked Integration-ready.</p></div>
        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-[0_20px_55px_rgba(15,23,42,.08)] sm:p-8" data-testid="hero-skill-graph"><div className="flex items-start justify-between border-b border-slate-100 pb-5"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.18em] text-[#A66D12]">AYUSH OCCUPATIONAL SKILL GRAPH</p><h2 className="mt-2 text-xl font-bold text-slate-900">One foundation. Many useful views.</h2></div><BadgeCheck className="text-[#174A3A]" /></div><div className="mt-7 space-y-3">{[["Student evidence", "Assessment and verified portfolio"], ["Skill connection", "GMP · Documentation · Clinical practice"], ["Opportunity fit", "Explainable match and next action"], ["Verified outcome", "Internship evidence and Career Passport"]].map(([label, copy], index) => <div key={label} className="grid grid-cols-[36px_1fr] gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full border border-amber-200 bg-amber-50 font-mono text-xs font-bold text-[#A66D12]">{index + 1}</div><div className="rounded-lg border border-slate-100 bg-slate-50 p-3"><p className="text-sm font-bold text-slate-900">{label}</p><p className="mt-1 text-xs text-slate-500">{copy}</p></div></div>)}</div></div>
      </div></section>

      <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8" data-testid="home-problem-section"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="font-mono text-xs font-semibold uppercase tracking-[0.16em] text-[#A66D12]">WHY SAMANVAYA</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-900">A shared language for AYUSH capability and opportunity.</h2></div><div className="grid gap-px overflow-hidden rounded-xl border border-slate-200 bg-slate-200 sm:grid-cols-3">{[["Students", "See where you fit and what to build next"], ["Industry", "Find capability through evidence, not prestige"], ["Institutions", "Read demand and close curriculum gaps"]].map(([title, copy]) => <div key={title} className="bg-white p-6"><h3 className="font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></div>)}</div></div></section>

      <section className="border-y border-slate-200 bg-slate-50" data-testid="home-loop-section"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><p className="font-mono text-xs font-semibold uppercase tracking-[0.16em] text-[#A66D12]">ASSESS → MATCH → MENTOR → WORK → VERIFY</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-900">A complete path from potential to proof.</h2><div className="mt-9 grid gap-4 md:grid-cols-5">{journey.map(({ label, copy, icon: Icon }, index) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-5" data-testid={`journey-step-${index + 1}`}><Icon size={19} className="text-[#A66D12]" /><p className="mt-5 text-lg font-bold text-slate-900">{label}</p><p className="mt-2 text-sm leading-6 text-slate-500">{copy}</p></div>)}</div></div></section>

      <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8" data-testid="home-opportunities-section"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono text-xs font-semibold uppercase tracking-[0.16em] text-[#A66D12]">YOJANA · EXPLAINABLE MATCHING</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-900">Every gap becomes a next action.</h2></div><Link to="/opportunities" className="inline-flex items-center gap-2 text-sm font-bold text-[#174A3A]" data-testid="featured-opportunities-link">View all opportunities <ArrowRight size={16} /></Link></div><div className="mt-8 grid gap-5 lg:grid-cols-2">{opportunities.slice(0, 2).map((opportunity) => <OpportunityCard key={opportunity.id} opportunity={opportunity} />)}</div></section>

      <section className="border-y border-slate-200 bg-[#FCFCFA]" data-testid="home-impact-section"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-16 sm:px-6 lg:grid-cols-3 lg:px-8">{[{ icon: Handshake, title: "Supported internships", copy: "Named mentors, concrete deliverables and two-sided check-ins." }, { icon: GraduationCap, title: "Portable evidence", copy: "Skills, projects and experience with visible provenance." }, { icon: Building2, title: "System insight", copy: "Aggregate institution and labour-market signals without exposing student data." }].map(({ icon: Icon, title, copy }) => <div key={title} className="border-l-2 border-[#C58B2A] pl-5"><Icon size={20} className="text-[#174A3A]" /><h3 className="mt-4 text-lg font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></div>)}</div></section>

      <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8" data-testid="home-final-cta"><div className="flex flex-col items-start justify-between gap-7 rounded-2xl border border-slate-200 bg-white p-8 shadow-[0_16px_45px_rgba(15,23,42,.06)] md:flex-row md:items-center"><div><p className="font-mono text-xs font-semibold uppercase tracking-[0.16em] text-[#A66D12]">YOUR NEXT STEP</p><h2 className="mt-2 text-3xl font-bold text-slate-900">Find your next opportunity. Build your next connection.</h2></div><div className="flex flex-wrap gap-3"><Link to="/demo/student" className="inline-flex h-11 items-center rounded-md border border-slate-300 px-5 text-sm font-bold text-slate-800" data-testid="final-demo-button">View demo</Link><Link to="/login" className="inline-flex h-11 items-center gap-2 rounded-md bg-[#174A3A] px-5 text-sm font-bold text-white" data-testid="final-cta-button">Open workspace <ArrowRight size={16} /></Link></div></div></section>
    </main>

    <footer className="border-t border-slate-200 bg-white" data-testid="site-footer"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 sm:px-6 md:grid-cols-[1.5fr_1fr_1fr] lg:px-8"><div><BrandMark testIdPrefix="home-footer" /><p className="mt-4 max-w-sm text-sm leading-6 text-slate-500">AYUSH Academia–Industry Skill Exchange · SIH 2026 product prototype.</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-[#A66D12]">Platform</p><div className="mt-4 space-y-3 text-sm text-slate-600"><Link to="/opportunities" className="block">Opportunities</Link><Link to="/alumni" className="block">Alumni</Link><Link to="/mentors" className="block">Mentors</Link></div></div><div><p className="text-xs font-bold uppercase tracking-wider text-[#A66D12]">Trust</p><div className="mt-4 space-y-3 text-sm text-slate-600"><Link to="/privacy" className="block">Privacy</Link><Link to="/accessibility" className="block">Accessibility</Link><Link to="/contact" className="block">Contact</Link></div></div></div><div className="border-t border-slate-100 px-4 py-5 text-center text-xs text-slate-500">© 2026 SAMANVAYA · Prototype, not an official Ministry service</div></footer>
  </div>;
}