import { Link, useParams } from "react-router-dom";
import SiteHeader from "@/components/SiteHeader";

const content: Record<string, { eyebrow: string; title: string; intro: string; sections: [string, string][] }> = {
  "how-it-works": { eyebrow: "HOW SAMANVAYA WORKS", title: "One skill graph. Many useful views.", intro: "SAMANVAYA is designed around the journey from potential to proof—not around a list of disconnected features.", sections: [["Assess with context", "Pariksha combines confidence, adaptive questions and verified evidence to show a more honest picture of readiness."], ["Match with a reason", "Yojana explains what matches, what is missing and which next step could make a role more reachable."], ["Work with support", "Karma turns an internship into a supported experience with a named mentor, a deliverable and check-ins."], ["Carry the proof forward", "Pramana gathers verified skills, experience and evidence into a portable career passport."]] },
  about: { eyebrow: "ABOUT SAMANVAYA", title: "Infrastructure for a more connected AYUSH ecosystem.", intro: "A product prototype for SIH 2026 Problem Statement 26044. The platform is designed to help people see pathways that conventional placement systems miss.", sections: [["Not a generic job portal", "AYUSH systems, skills, mentors, institutions and the realities of distributed enterprises are part of the product's core language."], ["Built with honesty", "All sample organisations, analytics and verification states in this prototype are clearly marked as demo data. Government and credential integrations are integration-ready, not live."], ["Designed for access", "The product direction includes vernacular expansion, low-bandwidth patterns, accessible interfaces and role-specific complexity."]] },
  faq: { eyebrow: "HELP CENTRE", title: "Clear answers for a clear next step.", intro: "This Phase 1 prototype keeps the important boundaries visible.", sections: [["Is this an official Ministry service?", "No. SAMANVAYA is a product prototype and does not represent an official Ministry service."], ["Is employer verification live?", "No. Verification states are simulated for the demo. A production verification layer is integration-ready."], ["Is authentication real?", "No. Demo personas are used in Phase 1. Real authentication is a Phase 2 dependency."], ["What happens to rejected applications?", "The intended experience turns a rejection into a useful next action, such as a skill gap or learning recommendation."]] },
  privacy: { eyebrow: "TRUST BY DESIGN", title: "Privacy is part of the product, not a footer link.", intro: "The prototype follows a consent-first direction and minimises what each role needs to see.", sections: [["Purpose limitation", "Student evidence should be shown only for a clear opportunity or mentoring purpose."], ["Scoped access", "Institution and Ministry views use aggregate signals rather than exposing individual student data unnecessarily."], ["Auditability", "A production build should record consent, access history, verification activity and changes to evidence."]] },
  accessibility: { eyebrow: "ACCESSIBILITY", title: "Useful to more people, by default.", intro: "SAMANVAYA targets WCAG 2.1 AA patterns across keyboard, screen reader, contrast, reduced motion and responsive layouts.", sections: [["Motion", "The cursor field is disabled for reduced-motion preferences and simplified on mobile."], ["Language", "The UI is structured for English first and future Hindi, Marathi, Tamil, Telugu, Kannada, Malayalam and Gujarati expansion."], ["Low bandwidth", "Core pages use restrained imagery, short content blocks, visible loading and retry patterns and simple responsive layouts."]] },
  contact: { eyebrow: "CONTACT", title: "Help shape the next connection.", intro: "For the prototype, use the demo workspace to explore the product story. Production contact and support channels are a Phase 4 dependency.", sections: [["Students and alumni", "Start with the student workspace and follow the assess → match → mentor → work → verify loop."], ["Institutions and employers", "Switch demo personas from the workspace header to preview institutional and employer views."], ["Prototype boundary", "No real submissions, messages, credentials or policy data are sent from this demo."]] },
};

export default function InfoPage() { const { slug = "about" } = useParams(); const page = content[slug] ?? content.about; return <div className="min-h-screen bg-[#F8FAF6]"><SiteHeader /><main className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8"><p className="font-mono text-xs font-semibold uppercase tracking-[0.18em] text-amber-700" data-testid="info-page-eyebrow">{page.eyebrow}</p><h1 className="mt-4 text-4xl font-bold tracking-tight text-[#0B3C2A] sm:text-5xl" data-testid="info-page-title">{page.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600" data-testid="info-page-intro">{page.intro}</p><div className="mt-12 divide-y divide-slate-200 rounded-xl border border-slate-200 bg-white">{page.sections.map(([heading, copy], index) => <section key={heading} className="p-6 sm:p-8" data-testid={`info-section-${index}`}><p className="font-mono text-xs font-semibold text-amber-700">0{index + 1}</p><h2 className="mt-3 text-xl font-bold text-[#0B3C2A]">{heading}</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-600">{copy}</p></section>)}</div><Link to="/app/student" className="mt-8 inline-flex items-center rounded-md bg-[#0B3C2A] px-5 py-3 text-sm font-bold text-white" data-testid="info-demo-workspace-link">Open demo workspace <span className="ml-2">→</span></Link></main></div>; }