import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Download, UserRound } from "lucide-react";
import DashboardShell from "@/components/DashboardShell";
import { apiGet, apiPost } from "@/lib/api";
import type { CheckInSummary, EvidencePack, PersistedInternship } from "@/lib/types";

export default function Karma() {
  const queryClient = useQueryClient();
  const internships = useQuery({ queryKey: ["internships", "me"], queryFn: () => apiGet<PersistedInternship[]>("/internships/me") });
  const internship = internships.data?.find((item) => item.week >= 4) ?? internships.data?.[0];
  const checkins = useQuery({ queryKey: ["check-ins", internship?.id, 4], queryFn: () => apiGet<CheckInSummary>(`/internships/${internship!.id}/check-ins?week=4`), enabled: Boolean(internship) });
  const [meetingFrequency, setMeetingFrequency] = useState<"Never" | "Once" | "Weekly">("Never");
  const [usefulFeedback, setUsefulFeedback] = useState<"Yes" | "Partially" | "No">("No");
  const [reflection, setReflection] = useState("I did not receive the scheduled weekly one-to-one review.");
  const submit = useMutation({ mutationFn: () => apiPost<CheckInSummary>(`/internships/${internship!.id}/check-ins`, { week: 4, meeting_frequency: meetingFrequency, useful_feedback: usefulFeedback, reflection }), onSuccess: (data) => { queryClient.setQueryData(["check-ins", internship?.id, 4], data); queryClient.invalidateQueries({ queryKey: ["internships", "me"] }); } });
  const evidence = useMutation({ mutationFn: () => apiGet<EvidencePack>(`/internships/${internship!.id}/evidence-pack`), onSuccess: (pack) => { const text = [`SAMANVAYA INTERNSHIP EVIDENCE PACK`, ``, `${pack.opportunity_title} · ${pack.organisation}`, ``, `Deliverable`, pack.deliverable, ``, `Performance metric`, pack.performance_metric, ``, `Mentor assessment`, pack.mentor_assessment, ``, `Student reflection`, pack.student_reflection, ``, `Status`, pack.completion_status, ``, `Generated ${new Date(pack.generated_at).toLocaleString()}`].join("\n"); const url = URL.createObjectURL(new Blob([text], { type: "text/plain" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "samanvaya-evidence-pack.txt"; anchor.click(); URL.revokeObjectURL(url); } });

  return <DashboardShell role="student" mode="real"><div className="mx-auto max-w-6xl px-4 py-10 sm:px-8" data-testid="karma-checkin-page">
    <p className="font-mono text-xs font-semibold uppercase tracking-[0.17em] text-[#A66D12]">KARMA · INTERNSHIP CONVERSION ENGINE</p>
    <h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">Make every check-in part of the evidence.</h1>
    <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Student and mentor responses are stored separately. Meaningful differences create a visible review signal for the institution.</p>
    {internships.isPending && <div className="mt-8 rounded-xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Loading your internship…</div>}
    {!internships.isPending && !internship && <div className="mt-8 rounded-xl border border-dashed border-slate-300 bg-white p-8"><h2 className="font-bold text-slate-900">No active internship yet.</h2><p className="mt-2 text-sm text-slate-500">Apply to an opportunity to create your milestone and check-in record.</p></div>}
    {internship && <>
      <section className="mt-8 grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
        <div className="rounded-xl border border-slate-200 bg-white p-6" data-testid="karma-internship-summary"><p className="text-xs font-bold uppercase tracking-wider text-[#A66D12]">ACTIVE EXPERIENCE · WEEK {internship.week}</p><h2 className="mt-3 text-2xl font-bold text-slate-900">{internship.opportunity_title}</h2><p className="mt-2 text-sm text-slate-600">{internship.organisation} · Mentor: {internship.mentor}</p><div className="mt-6 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#C58B2A]" style={{ width: `${Math.round((internship.week / internship.total_weeks) * 100)}%` }} /></div><p className="mt-3 text-xs text-slate-500">{internship.week} of {internship.total_weeks} weeks</p></div>
        <div className={`rounded-xl border p-6 ${checkins.data?.divergence_alert ? "border-amber-300 bg-amber-50" : "border-slate-200 bg-white"}`} data-testid="karma-divergence-status">{checkins.data?.divergence_alert ? <><AlertTriangle className="text-[#A66D12]" /><h2 className="mt-4 font-bold text-slate-900">Divergence detected</h2><p className="mt-2 text-sm leading-6 text-slate-600">Student and mentor meeting reports differ. Institution review is recommended.</p></> : <><CheckCircle2 className="text-[#174A3A]" /><h2 className="mt-4 font-bold text-slate-900">Check-in aligned</h2><p className="mt-2 text-sm text-slate-600">No two-sided divergence is currently recorded.</p></>}</div>
      </section>
      <section className="mt-6 grid gap-6 lg:grid-cols-2">
        <form onSubmit={(event) => { event.preventDefault(); submit.mutate(); }} className="rounded-xl border border-slate-200 bg-white p-6" data-testid="student-checkin-form"><h2 className="text-xl font-bold text-slate-900">Week 4 student check-in</h2><p className="mt-1 text-sm text-slate-500">Your response remains distinct from the mentor’s response.</p><label className="mt-6 block text-sm font-semibold text-slate-700">How often did you meet your mentor?<select value={meetingFrequency} onChange={(event) => setMeetingFrequency(event.target.value as typeof meetingFrequency)} className="mt-2 h-11 w-full rounded-md border border-slate-300 bg-white px-3 font-normal" data-testid="checkin-meeting-select"><option>Never</option><option>Once</option><option>Weekly</option></select></label><label className="mt-4 block text-sm font-semibold text-slate-700">Are you receiving useful feedback?<select value={usefulFeedback} onChange={(event) => setUsefulFeedback(event.target.value as typeof usefulFeedback)} className="mt-2 h-11 w-full rounded-md border border-slate-300 bg-white px-3 font-normal" data-testid="checkin-feedback-select"><option>Yes</option><option>Partially</option><option>No</option></select></label><label className="mt-4 block text-sm font-semibold text-slate-700">Reflection<textarea value={reflection} onChange={(event) => setReflection(event.target.value)} className="mt-2 min-h-28 w-full rounded-md border border-slate-300 p-3 font-normal" data-testid="checkin-reflection-input" /></label><button disabled={submit.isPending} className="mt-5 w-full rounded-md bg-[#174A3A] py-3 text-sm font-bold text-white disabled:opacity-60" data-testid="checkin-submit-button">{submit.isPending ? "Saving…" : "Submit student check-in"}</button></form>
        <div className="rounded-xl border border-slate-200 bg-white p-6" data-testid="mentor-checkin-card"><div className="flex items-center gap-2"><UserRound size={18} className="text-[#A66D12]" /><h2 className="text-xl font-bold text-slate-900">Mentor response</h2></div>{checkins.data?.mentor ? <div className="mt-6 space-y-4"><div><p className="text-xs font-semibold uppercase text-slate-500">Meeting frequency</p><p className="mt-1 font-bold text-slate-900">{checkins.data.mentor.meeting_frequency}</p></div><div><p className="text-xs font-semibold uppercase text-slate-500">Useful feedback provided</p><p className="mt-1 font-bold text-slate-900">{checkins.data.mentor.useful_feedback}</p></div><div><p className="text-xs font-semibold uppercase text-slate-500">Mentor note</p><p className="mt-1 text-sm leading-6 text-slate-600">{checkins.data.mentor.reflection}</p></div></div> : <p className="mt-6 text-sm text-slate-500">Mentor response pending.</p>}<button onClick={() => evidence.mutate()} disabled={evidence.isPending} className="mt-8 inline-flex w-full items-center justify-center gap-2 rounded-md border border-[#174A3A] py-3 text-sm font-bold text-[#174A3A] disabled:opacity-60" data-testid="evidence-pack-download-button"><Download size={16} />{evidence.isPending ? "Preparing…" : "Download evidence pack"}</button><p className="mt-3 text-center text-[11px] text-slate-500">Generated from saved milestone and check-in records.</p></div>
      </section>
    </>}
  </div></DashboardShell>;
}