import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowRight, BadgeCheck, BookOpenCheck, ExternalLink, Filter, GitBranch } from "lucide-react";
import DashboardShell from "@/components/DashboardShell";
import { apiGet } from "@/lib/api";
import type { AssessmentResult, StudentProfile } from "@/lib/types";

type Certification = { system: string; gaps: string[]; title: string; provider: string; level: string; url: string };

const certifications: Certification[] = [
  { system: "Ayurveda", gaps: ["Panchakarma", "Infection prevention"], title: "Panchakarma Assistant — HSS/Q3603", provider: "Healthcare Sector Skill Council", level: "NSQF Level 3", url: "https://www.healthcare-ssc.in/pdf/New25/MC_Panchakarma_Assistant.pdf" },
  { system: "Ayurveda", gaps: ["Clinical operations", "Patient communication"], title: "Ayurveda Masseur — HSS/Q3605", provider: "Healthcare Sector Skill Council", level: "NSQF Level 2.5", url: "https://www.healthcare-ssc.in/pdf/New25/QP_Ayurveda_Masseur.pdf" },
  { system: "Ayurveda", gaps: ["Panchakarma", "Clinical evidence"], title: "Panchakarma Technician Certificate Course", provider: "National Institute of Ayurveda", level: "Institution certificate", url: "https://nia.nic.in/pdf/Panchkarma_Technician_Certificate_Course_11feb25.pdf" },
  { system: "Ayurveda", gaps: ["Panchakarma", "Safe practice"], title: "Panchakarma Assistant — Course 666", provider: "National Institute of Open Schooling", level: "Vocational course", url: "https://rcallahabad.nios.ac.in/panchakarma-assistant-666.html" },
  { system: "Yoga & Naturopathy", gaps: ["Patient education", "Wellness"], title: "Yoga Wellness Instructor", provider: "Yoga Certification Board", level: "Yoga education & training pathway", url: "https://yogacertificationboard.nic.in/" },
  { system: "Yoga & Naturopathy", gaps: ["Communication", "Wellness"], title: "Yoga Protocol Instructor", provider: "Yoga Certification Board", level: "Voluntary certification scheme", url: "https://yogacertificationboard.nic.in/frequently-asked-questions/" },
];

export default function SkillGraph() {
  const profile = useQuery({ queryKey: ["profile", "me"], queryFn: () => apiGet<StudentProfile>("/profile/me") });
  const latest = useQuery({ queryKey: ["assessment", "latest"], queryFn: () => apiGet<AssessmentResult | null>("/assessments/latest") });
  const [system, setSystem] = useState("All systems");
  const [skillGap, setSkillGap] = useState("All skill gaps");
  const [provider, setProvider] = useState("All providers");
  const currentGap = latest.data?.gaps[0] ?? "GMP fundamentals";
  const skillOptions = Array.from(new Set(certifications.flatMap((item) => item.gaps))).sort();
  const providerOptions = Array.from(new Set(certifications.map((item) => item.provider))).sort();
  const filtered = useMemo(() => certifications.filter((item) => (system === "All systems" || item.system === system) && (skillGap === "All skill gaps" || item.gaps.includes(skillGap)) && (provider === "All providers" || item.provider === provider)), [system, skillGap, provider]);

  return <DashboardShell role="student" mode="real"><div className="mx-auto max-w-6xl px-4 py-10 sm:px-8" data-testid="skill-graph-page">
    <p className="font-mono text-xs font-semibold uppercase tracking-[0.17em] text-[#A66D12]">LAYER 0 · AYUSH SKILL GRAPH</p><h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">See how one skill opens the next role.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Your profile and Pariksha evidence shape this pathway. Certification suggestions link to authoritative providers; SAMANVAYA does not enrol or verify them.</p>
    <section className="mt-8 rounded-xl border border-slate-200 bg-white p-6 sm:p-8" data-testid="skill-graph-visual"><div className="flex items-center gap-2 text-sm font-semibold text-[#174A3A]"><GitBranch size={18} />Recommended pathway for {profile.data?.name ?? "your profile"}</div><div className="mt-7 grid gap-3 md:grid-cols-5">{["AYUSH foundation", currentGap, "Verified learning", "Evidence-led internship", "Career role"].map((node, index) => <div key={`${node}-${index}`} className="relative rounded-lg border border-slate-200 bg-slate-50 p-4" data-testid={`skill-graph-node-${index}`}><span className="font-mono text-[10px] text-[#A66D12]">0{index + 1}</span><p className="mt-2 text-sm font-bold text-slate-900">{node}</p>{index < 4 && <ArrowRight className="absolute -right-5 top-1/2 z-10 hidden -translate-y-1/2 text-[#A66D12] md:block" size={20} />}</div>)}</div><div className="mt-6 rounded-lg border-l-4 border-[#C58B2A] bg-amber-50 p-4 text-sm text-amber-950" data-testid="skill-graph-gap-note"><strong>Why this path:</strong> {currentGap} is a current assessment gap. Use the filters below to find a credible learning route.</div></section>
    <section className="mt-10" data-testid="certification-recommendations"><div className="flex items-end justify-between gap-4"><div><p className="font-mono text-xs font-semibold uppercase tracking-[0.15em] text-[#A66D12]">CREDIBLE NEXT STEPS</p><h2 className="mt-2 text-2xl font-bold text-slate-900">Certification and training sources</h2></div><BadgeCheck className="text-[#174A3A]" /></div>
      <div className="mt-5 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 md:grid-cols-[auto_1fr_1fr_1fr]" data-testid="certification-filter-bar"><div className="flex items-center gap-2 text-sm font-bold text-slate-700"><Filter size={16} />Filter</div><label className="text-xs font-semibold text-slate-600">AYUSH system<select value={system} onChange={(event) => setSystem(event.target.value)} className="mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-3 text-sm font-normal" data-testid="certification-system-filter"><option>All systems</option><option>Ayurveda</option><option>Yoga & Naturopathy</option></select></label><label className="text-xs font-semibold text-slate-600">Skill gap<select value={skillGap} onChange={(event) => setSkillGap(event.target.value)} className="mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-3 text-sm font-normal" data-testid="certification-skill-filter"><option>All skill gaps</option>{skillOptions.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Provider<select value={provider} onChange={(event) => setProvider(event.target.value)} className="mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-3 text-sm font-normal" data-testid="certification-provider-filter"><option>All providers</option>{providerOptions.map((item) => <option key={item}>{item}</option>)}</select></label></div>
      <p className="mt-4 text-sm text-slate-500" data-testid="certification-result-count">{filtered.length} authoritative sources match these filters</p>
      <div className="mt-4 grid gap-5 lg:grid-cols-3">{filtered.map((item) => { const index = certifications.indexOf(item); return <article key={item.title} className="rounded-xl border border-slate-200 bg-white p-6" data-testid={`certification-card-${index}`}><BookOpenCheck size={20} className="text-[#A66D12]" /><div className="mt-5 flex items-center justify-between gap-2"><p className="text-xs font-semibold uppercase tracking-wider text-[#A66D12]">{item.system}</p><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] text-slate-600">{item.gaps[0]}</span></div><h3 className="mt-2 text-lg font-bold text-slate-900">{item.title}</h3><p className="mt-2 text-sm text-slate-600">{item.provider}</p><p className="mt-1 text-xs text-slate-500">{item.level}</p><a href={item.url} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#174A3A]" data-testid={`certification-source-link-${index}`}>Open official source <ExternalLink size={14} /></a><p className="mt-3 text-[11px] leading-5 text-slate-500">Verify current eligibility, intake, fees, availability and recognition directly with the provider before applying.</p></article>; })}</div>
      {filtered.length === 0 && <div className="mt-5 rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center" data-testid="certification-empty-state"><p className="font-semibold text-slate-900">No source matches all three filters.</p><button onClick={() => { setSystem("All systems"); setSkillGap("All skill gaps"); setProvider("All providers"); }} className="mt-3 text-sm font-bold text-[#174A3A]" data-testid="certification-clear-filters">Clear filters</button></div>}
    </section>
  </div></DashboardShell>;
}